version: '3.8'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile.bun
    tty: true
    volumes:
      - ../:/home/user/app
    networks:
      - chat-app-network
    environment:
      - WATCHPACK_POLLING=true

networks:
  chat-app-network:
    external: true
